# want, tracked — data collection

## research question

how does social media shape consumer desire, and what can online attention reveal about the growing influence of places like japan and new york on fashion, travel, food, and lifestyle trends?

## purpose

this notebook collects search-interest data for selected places, products, foods, and fashion trends. the goal is to measure how online attention changes over time and later compare patterns in growth, longevity, volatility, and similarity across trends.

google trends measures relative search interest rather than purchases or direct social media activity, so the data will be treated as a measure of online attention rather than proof of consumer demand or causation.

## candidate variables

the project begins with two major cultural reference points: japan and new york city. rather than treating these places as the direct cause of individual trends, they are used as case studies for exploring how place, online attention, and consumer taste can overlap.

### japan / tokyo
- japan travel
- tokyo travel
- onitsuka tiger
- asics
- matcha
- digital camera

### new york city
- new york travel
- nyc fashion
- jorts
- coach

### broader consumer trends
additional fashion, food, and lifestyle trends will be tested and added based on data availability and their relevance to the research question.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from pytrends.request import TrendReq

print("libraries loaded successfully")

libraries loaded successfully

/Users/shraddha/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [3]:
trends = pd.DataFrame({
    "trend": [
        "Onitsuka Tiger",
        "Japan travel",
        "Tokyo travel",
        "ASICS",
        "Matcha",
        "Digital cameras",
        "New York travel",
        "NYC fashion",
        "Jorts",
        "Coach"
    ],
    
    "category": [
        "fashion",
        "travel",
        "travel",
        "fashion",
        "food",
        "lifestyle",
        "travel",
        "fashion",
        "fashion",
        "fashion"
    ],
    
    "cultural_reference": [
        "Japan",
        "Japan",
        "Japan",
        "Japan",
        "Japan",
        "Japan",
        "New York",
        "New York",
        "New York",
        "New York"
    ]
})

trends

             trend   category cultural_reference
0   Onitsuka Tiger    fashion              Japan
1     Japan travel     travel              Japan
2     Tokyo travel     travel              Japan
3            ASICS    fashion              Japan
4           Matcha       food              Japan
5  Digital cameras  lifestyle              Japan
6  New York travel     travel           New York
7      NYC fashion    fashion           New York
8            Jorts    fashion           New York
9            Coach    fashion           New York

## planned trend measurements

each selected trend will eventually receive a data-driven profile based on its attention pattern over time.

the initial measurements will include:

- **growth:** how much attention increases during a trend's rise
- **peak:** the period with the highest observed attention
- **longevity:** how long elevated attention persists
- **decline:** how quickly attention falls after its peak
- **volatility:** how dramatically attention changes over time
- **momentum:** whether recent attention is increasing, stable, or decreasing

these measurements will be used to compare trends without assuming that search or online attention is equivalent to purchasing behavior.

## data sources

### internet trend signals

the project will use publicly available trend and search-interest data to study changes in online attention across fashion, travel, food, and lifestyle.

pinterest trend reports and other public sources will be used to identify emerging consumer interests and compare how different trends grow, peak, and spread across categories.

additional economic or tourism data may be added later as supporting evidence when it helps explain a specific trend, rather than serving as the project's main dataset.

In [6]:
candidate_trends = pd.DataFrame({
    "trend": [
        "Onitsuka Tiger",
        "Japan travel",
        "Tokyo shopping",
        "Issey Miyake",
        "Matcha",
        "Digital cameras",
        "Vintage watches",
        "Ballet flats",
        "Adidas Taekwondo",
        "Track shorts",
        "Jorts",
        "Coach",
        "Rhode",
        "NYC travel",
        "Vintage shopping"
    ],

    "category": [
        "fashion",
        "travel",
        "travel",
        "fashion",
        "food",
        "lifestyle",
        "fashion",
        "fashion",
        "fashion",
        "fashion",
        "fashion",
        "fashion",
        "beauty",
        "travel",
        "fashion"
    ],

    "cultural_world": [
        "Tokyo",
        "Japan",
        "Tokyo",
        "Tokyo",
        "Japan",
        "internet culture",
        "Tokyo / NYC",
        "NYC",
        "NYC",
        "NYC",
        "NYC",
        "NYC",
        "internet culture",
        "NYC",
        "Tokyo / NYC"
    ]
})

candidate_trends

               trend   category    cultural_world
0     Onitsuka Tiger    fashion             Tokyo
1       Japan travel     travel             Japan
2     Tokyo shopping     travel             Tokyo
3       Issey Miyake    fashion             Tokyo
4             Matcha       food             Japan
5    Digital cameras  lifestyle  internet culture
6    Vintage watches    fashion       Tokyo / NYC
7       Ballet flats    fashion               NYC
8   Adidas Taekwondo    fashion               NYC
9       Track shorts    fashion               NYC
10             Jorts    fashion               NYC
11             Coach    fashion               NYC
12             Rhode     beauty  internet culture
13        NYC travel     travel               NYC
14  Vintage shopping    fashion       Tokyo / NYC

In [7]:
candidate_trends["desire_type"] = [
    "brand",       # Onitsuka Tiger
    "place",       # Japan travel
    "experience",  # Tokyo shopping
    "brand",       # Issey Miyake
    "food",        # Matcha
    "object",      # Digital cameras
    "object",      # Vintage watches
    "product",     # Ballet flats
    "product",     # Adidas Taekwondo
    "product",     # Track shorts
    "product",     # Jorts
    "brand",       # Coach
    "brand",       # Rhode
    "place",       # NYC travel
    "experience"   # Vintage shopping
]

candidate_trends

               trend   category    cultural_world desire_type
0     Onitsuka Tiger    fashion             Tokyo       brand
1       Japan travel     travel             Japan       place
2     Tokyo shopping     travel             Tokyo  experience
3       Issey Miyake    fashion             Tokyo       brand
4             Matcha       food             Japan        food
5    Digital cameras  lifestyle  internet culture      object
6    Vintage watches    fashion       Tokyo / NYC      object
7       Ballet flats    fashion               NYC     product
8   Adidas Taekwondo    fashion               NYC     product
9       Track shorts    fashion               NYC     product
10             Jorts    fashion               NYC     product
11             Coach    fashion               NYC       brand
12             Rhode     beauty  internet culture       brand
13        NYC travel     travel               NYC       place
14  Vintage shopping    fashion       Tokyo / NYC  experience

In [8]:
candidate_trends["trend_id"] = (
    candidate_trends["trend"]
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("/", "_", regex=False)
)

final_metadata = candidate_trends[
    ["trend_id", "trend", "category", "cultural_world", "desire_type"]
]

final_metadata.to_csv("../data/trend_metadata.csv", index=False)

final_metadata

,trend_id,trend,category,cultural_world,desire_type
0,onitsuka_tiger,Onitsuka Tiger,fashion,Tokyo,brand
1,japan_travel,Japan travel,travel,Japan,place
2,tokyo_shopping,Tokyo shopping,travel,Tokyo,experience
3,issey_miyake,Issey Miyake,fashion,Tokyo,brand
4,matcha,Matcha,food,Japan,food
5,digital_cameras,Digital cameras,lifestyle,internet culture,object
6,vintage_watches,Vintage watches,fashion,Tokyo / NYC,object
7,ballet_flats,Ballet flats,fashion,NYC,product
8,adidas_taekwondo,Adidas Taekwondo,fashion,NYC,product
9,track_shorts,Track shorts,fashion,NYC,product
10,jorts,Jorts,fashion,NYC,product
11,coach,Coach,fashion,NYC,brand
12,rhode,Rhode,beauty,internet culture,brand
13,nyc_travel,NYC travel,travel,NYC,place
14,vintage_shopping,Vintage shopping,fashion,Tokyo / NYC,experience

In [9]:
import requests

In [10]:
def get_wikipedia_pageviews(article, start="20210101", end="20260701"):
    article = article.replace(" ", "_")

    url = (
        "https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/"
        f"en.wikipedia.org/all-access/user/{article}/monthly/{start}/{end}"
    )

    headers = {
        "User-Agent": "want-tracked-data-project/1.0"
    }

    response = requests.get(url, headers=headers)
    response.raise_for_status()

    data = response.json()["items"]

    return pd.DataFrame({
        "date": pd.to_datetime(
            [item["timestamp"][:6] for item in data],
            format="%Y%m"
        ),
        "views": [item["views"] for item in data],
        "article": article.replace("_", " ")
    })

In [11]:
onitsuka_views = get_wikipedia_pageviews("Onitsuka Tiger")

onitsuka_views.tail()

         date  views         article
62 2026-03-01  25528  Onitsuka Tiger
63 2026-04-01  32135  Onitsuka Tiger
64 2026-05-01  27655  Onitsuka Tiger
65 2026-06-01  26908  Onitsuka Tiger
66 2026-07-01    717  Onitsuka Tiger

In [12]:
onitsuka_views = onitsuka_views[
    onitsuka_views["date"] < "2026-07-01"
]

onitsuka_views.tail()

         date  views         article
61 2026-02-01  22296  Onitsuka Tiger
62 2026-03-01  25528  Onitsuka Tiger
63 2026-04-01  32135  Onitsuka Tiger
64 2026-05-01  27655  Onitsuka Tiger
65 2026-06-01  26908  Onitsuka Tiger

In [13]:
onitsuka_views.to_csv(
    "../data/raw/onitsuka_tiger_pageviews.csv",
    index=False
)

print("saved onitsuka tiger pageviews!")

saved onitsuka tiger pageviews!

In [18]:
articles = {
    "onitsuka_tiger": "Onitsuka Tiger",
    "uniqlo": "Uniqlo",
    "matcha": "Matcha",
    "digital_cameras": "Digital camera",
    "jorts": "Jean shorts"
}

print("ready to collect", len(articles), "more trends")

ready to collect 5 more trends

In [19]:
all_pageviews = []

for trend_id, article in articles.items():
    try:
        pageviews = get_wikipedia_pageviews(article)

        # remove incomplete july 2026 observations
        pageviews = pageviews[pageviews["date"] < "2026-07-01"]

        # identify each trend in the combined dataset
        pageviews["trend_id"] = trend_id

        all_pageviews.append(pageviews)

        print(f"✓ successfully collected {article}")

    except Exception as e:
        print(f"✗ unable to collect {article}")
        print(e)

✓ successfully collected Onitsuka Tiger
✓ successfully collected Uniqlo
✓ successfully collected Matcha
✓ successfully collected Digital camera
✓ successfully collected Jean shorts

### refining the first attention sample

the first attention sample was revised to better match the project's central question about how places and cultural influence shape consumer desire.

coach was removed from the initial sample and replaced with uniqlo. while coach is relevant to fashion and brand revival, uniqlo creates a clearer connection between japanese consumer culture and global fashion demand. it also gives the japan case study another type of brand to compare with onitsuka tiger.

the first sample therefore includes onitsuka tiger, uniqlo, matcha, digital cameras, and jorts. these trends represent a mix of brands, food, objects, and fashion rather than one single type of consumer trend.

this selection may still be refined later if a source does not provide enough reliable historical data.

In [20]:
pageviews_df = pd.concat(all_pageviews, ignore_index=True)

pageviews_df = pageviews_df.sort_values(
    ["trend_id", "date"]
).reset_index(drop=True)

pageviews_df.head()

        date  views         article         trend_id
0 2021-01-01  24535  Digital camera  digital_cameras
1 2021-02-01  25308  Digital camera  digital_cameras
2 2021-03-01  27077  Digital camera  digital_cameras
3 2021-04-01  23590  Digital camera  digital_cameras
4 2021-05-01  21860  Digital camera  digital_cameras

In [21]:
pageviews_df.to_csv(
    "../data/raw/wikipedia_pageviews.csv",
    index=False
)

print("wikipedia pageviews dataset saved!")

wikipedia pageviews dataset saved!

## creating trend profiles

the monthly pageview dataset contains detailed observations for each trend over time. to better compare trends, the data will be summarized into a trend profile.

each profile captures key measures of consumer attention, including average attention, peak attention, growth over time, and volatility. these metrics make it possible to compare different types of trends and explore how online attention relates to consumer demand.

In [22]:
trend_profiles = (
    pageviews_df
    .groupby("trend_id")
    .agg(
        average_attention=("views", "mean"),
        peak_attention=("views", "max"),
        lowest_attention=("views", "min"),
        total_attention=("views", "sum"),
        volatility=("views", "std")
    )
    .round(2)
)

trend_profiles

,average_attention,peak_attention,lowest_attention,total_attention,volatility
trend_id,,,,,
digital_cameras,17146.06,27077,8996,1131640,4731.35
jorts,40.97,266,8,2704,38.91
matcha,87660.85,180360,51510,5785616,33212.78
onitsuka_tiger,24721.05,115309,13162,1631589,12855.77
uniqlo,46100.55,85945,26889,3042636,12966.61

### measuring trend growth

average attention and peak attention describe how popular a trend is, but they do not show whether interest is increasing or decreasing over time.

to measure changes in consumer attention, the first and last observations for each trend will be compared. this provides a simple measure of growth that can later be used to discuss changes in consumer demand.

In [23]:
growth = (
    pageviews_df
    .groupby("trend_id")
    .agg(
        first_attention=("views", "first"),
        latest_attention=("views", "last")
    )
)

growth["percent_growth"] = (
    (
        growth["latest_attention"] - growth["first_attention"]
    ) / growth["first_attention"]
) * 100

growth = growth.round(2)

growth

                 first_attention  latest_attention  percent_growth
trend_id
digital_cameras            24535              8996          -63.33
jorts                         29                65          124.14
matcha                     79069             63858          -19.24
onitsuka_tiger             18803             26908           43.10
uniqlo                     29407             35801           21.74

In [24]:
trend_profiles = trend_profiles.join(growth)

trend_profiles

,average_attention,peak_attention,lowest_attention,total_attention,volatility,first_attention,latest_attention,percent_growth
trend_id,,,,,,,,
digital_cameras,17146.06,27077,8996,1131640,4731.35,24535,8996,-63.33
jorts,40.97,266,8,2704,38.91,29,65,124.14
matcha,87660.85,180360,51510,5785616,33212.78,79069,63858,-19.24
onitsuka_tiger,24721.05,115309,13162,1631589,12855.77,18803,26908,43.10
uniqlo,46100.55,85945,26889,3042636,12966.61,29407,35801,21.74

In [25]:
trend_profiles.to_csv(
    "../data/trend_profiles.csv",
    index=True
)

print("trend profiles saved!")

trend profiles saved!